= Instalação do Cygwin
:author: Paulo Jerônimo
:email: paulojeronimo@gmail.com

== Motivação

A instalação do http://cygwin.com[Cygwin] no Windows oferece facilidade na instalação de várias ferramentas que serão utilizadas na montagem de um ambiente Java EE mais profissional. No contexto desse projeto (`javaee-ambiente`) ele é necessário para a execução de scripts (escritos em Bash) que automatizam a instalação e facilitam o uso de diversas ferramentas. Além disso, é através do Cygwin que são instalados o Git, o Vim, o Tmux, dentre outros.

== Instalação

Neste tutorial, será exemplificada a instalação da versão do Cygwin num Windows 64 bits.

Faça o download do executável de instalação do Cygwin https://cygwin.com/setup-x86_64.exe[(setup-x86_64.exe)] para o diretório `Downloads` de teu usuário. 

Abra o prompt de comando do Windows (`cmd.exe`) e execute:

----
cd %USERPROFILE%\Downloads
setup-x86_64.exe -q -P wget
----

Como sugestão para pasta local onde serão mantidos os downloads realizados pelo Cygwin utilize `C:\cygwin64.packages`.

Como sugestão de `mirror` de onde serão realizados os downloads do Cygwin utilize http://mirrors.kernel.org (se ele estiver disponível na lista apresentada).


== Mudança do HOME para o diretório apontado por USERPROFILE

Abra o Cygwin e execute:

[source,bash]
----
mkpasswd -l -d -p "$(cygpath -H)" > /etc/passwd
logout
----

Reinicie o Cygwin e execute:

[source,bash]
----
shopt -s dotglob
mv /home/$USER/* ~
rm -rf /home/$USER
logout
----

== Ajuste do encoding para UTF-8

Para ajustar o suporte para UTF-8 (em português do Brasil (pt_BR)), reabra um shell do Cygwin e execute:

[source,bash]
----
echo 'export LANG=pt_BR.UTF-8' >> ~/.bashrc
logout
----

Reinicie novamente o Cygwin e confira o encoding com o comando `locale`, como no exemplo a seguir:

----
$ locale
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_ALL=
----

== Instalação do apt-cyg

O utilitário `apt-cyg` é um gerenciador de pacotes que funciona via linha de comando, assim como o `yum` (no Fedora) ou o `apt-get` (em distribuições derivadas do Debian). Reinicie novamente o Cygwin e execute:

[source,bash]
----
lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > /tmp/apt-cyg
install /tmp/apt-cyg /bin
----

== Instalação de pacotes (essenciais e úteis)

[source,bash]
----
apt-cyg install git zip patch vim tree unzip procps
----

== Procedimentos para remoção do Gygwin (instalado em C:/cygwin64)

. Abrir o "Prompt de Comando (Admin)"
. Executar os seguintes comandos:
[source]
----
takeown /f C:\cygwin64 /r /d Y
icacls c:\cygwin64 /T /Q /C /reset
rmdir /s /q C:\cygwin64
----

== Referências

* https://cygwin.com/cygwin-ug-net/setup-locale.html
* https://github.com/transcode-open/apt-cyg
* http://stackoverflow.com/questions/9260014/how-do-i-install-cygwin-components-from-the-command-line
* http://jgoodall.me/posts/2013/05/29/git-use-https/

